### ISSUE TITLE
Why is CurrentDirectory needed?

### ISSUE THREAD

**Issue by dazinator** [kthompson/csharp-glob#2]
I wanted to just match some strings using globbing, so don't want to involve System.IO at all.

However I noticed that when using
```

  var glob = new Glob(somePattern);
  var isMatch = glob.IsMatch(someString);

```

It calls this in the Parser:

```
      private GlobNode ParseRoot()
        {
            if (this._currentToken.Kind == TokenKind.PathSeperator)
                return new GlobNode(GlobNodeType.Root); //dont eat it so we can leave it for the segments


            if (this._currentToken.Kind == TokenKind.Identifier &&
                this._currentToken.Spelling.Length == 1 &&
                this._scanner.Peek().Kind == TokenKind.WindowsRoot)
            {
                var ident = this.ParseIdentifier();
                this.Accept(TokenKind.WindowsRoot);
                return new GlobNode(GlobNodeType.Root, ident);
            }           

           return new GlobNode(GlobNodeType.Root, Directory.GetCurrentDirectory());
        }
```

Notice the call to Directory.GetCurrentDirectory().

I am a bit confused as to why the current Directory is needed.

I tried adjusting it to this:

```
return new GlobNode(GlobNodeType.Root)
```

This let's it proceed without touching the directory - however I  notice now that if I try and use the following pattern match I get an exception:

```

  var glob = new Glob("*file.txt");
  var isMatch = glob.IsMatch("/file.txt");

```

The Parse() method falls over because when it Parses the root it is expecting to parse a directory structure, ending with an EOT token

```
 public GlobNode Parse(string text = null)
        {
            if (text != null)
                this._scanner = new Scanner(text);

            this.AcceptIt();
            var path = this.ParseTree();
            if (this._currentToken.Kind != TokenKind.EOT)
            {
                throw new Exception("Expected EOT");
            }

            return path;
        }

```

However the current token kind is `Wildcard` because the pattern I am parsing is `*file.txt` so the first character is a wildcard, not a directory seperator..

Not really sure how to proceed.. Any tips?

**Comment by dazinator** [comment]
It seems the parser won't currently handle patterns that don't start with a recognised root. So `c://*something` will work, so will `/*something` but `*something` won't currently work.

I'm not sure of the easiest way to add support for non rooted patterns is, so for now I have just changed the patterns I am passing it to use a root character, so rather than `*file.txt` I use `/*file.txt` as the pattern.

**Comment by dazinator** [comment]
Ok I fixed this in the parser now. The ParseTree() method expects the current character to be a path seperator after parsing the "root".

However given a pattern without a root, like: `*somefile.txt` this isn't the case. Due to this, it doesn't continue to parse the rest of the segments of the pattern.

The solution I went with was to amend ParseTree() method, so that after parsing the root, it always Accepts it, irresepctive of what the current character is. It then proceeds to parse the first segment irrespective of what the current character is having parsed the root. Only then, does it expect each following segment to start with a path seperator character.  

Here is the updated ParseTree() method:

```
       private GlobNode ParseTree()
        {
            var items = new List<GlobNode>();

            items.Add(this.ParseRoot());
            // accept the root, and parse the first segment regardless of what the current character is.
            // this allows patterns to be used that don't start with a root, i.e `*somefile.txt`
            this.AcceptIt();
            items.Add(this.ParseSegment());
            // all subsequent segments should be seperated with a path seperator.
            while (this._currentToken.Kind == TokenKind.PathSeperator)
            {
                this.AcceptIt();
                items.Add(this.ParseSegment());
            }

            return new GlobNode(GlobNodeType.Tree, items);
        }

```

Updated ParseRoot() method:

```
  private GlobNode ParseRoot()
        {
            if (this._currentToken.Kind == TokenKind.PathSeperator)
                return new GlobNode(GlobNodeType.Root); //dont eat it so we can leave it for the segments


            if (this._currentToken.Kind == TokenKind.Identifier &&
                this._currentToken.Spelling.Length == 1 &&
                this._scanner.Peek().Kind == TokenKind.WindowsRoot)
            {
                var ident = this.ParseIdentifier();
                this.Accept(TokenKind.WindowsRoot);
                return new GlobNode(GlobNodeType.Root, ident);
            }          
            return new GlobNode(GlobNodeType.Root);
      
        }
```

**Comment by kthompson** [comment]
I made a small modification on master that will return a WindowsRoot as a single token that includes the whole "c:" part. This should make updating Parse to support non root as the first parameter. I will try to make some of these changes today.

**Comment by kthompson** [comment]
I updated master so that the a Root is now optional, also allows a single Segment to occur as a tree.

so something like
`tree := root? ("/" segment)* segment?`

Let me know if this doesnt resolve your issues. Would be worth adding a lot more unit tests.
